### ISSUE TITLE
Viewing MathJax Markup Code

### ISSUE THREAD

**Issue by mhubig** [feedbin/support#395]
Hi @benubois,

i've found some Problems viewing a post (http://what-if.xkcd.com/71/) with MathJax Markup Code:

![screenshot 2013-11-12 11 35 21](https://f.cloud.github.com/assets/219704/1520961/747de98a-4b87-11e3-92f8-e8c5999ee49b.png)

It doesn't even show up right in "Couch-Mode":

![screenshot 2013-11-12 11 46 41](https://f.cloud.github.com/assets/219704/1520972/c2878802-4b87-11e3-86a6-33fe553cd06c.png)

**Comment by OJFord** [comment]
I also have this issue, and haven't been able to find a Chrome or FF extension that works - presumably because Mercury's parsing breaks the original formatting?

Relatedly, it's also not possible to read `pre`-formatted code snippets in 'full-content load'ed articles, (Mercury strips the whitespace) and JS-embedded snippets are broken in multi-column views due to no horizontal scroll.

Was Zegnat's proposal decided against, or is this just a low-priority nice-to-have?

> what Feedbin probably has to do to get MathJax right:
> 1. Include MathJax, either in `<head>` or load it dynamically.
> 2. Use `skipStartupTypeset` configuration to stop it from parsing anything until you want it to. (Source.) It might be required to set `delayStartupUntil` also.
> 3. Limit MathJax to article content only by setting the elements configuration to e.g. `document.getElementsByClassName('content-styles')`.
> 4. When article content has been loaded do `MathJax.Hub.Queue(["Typeset",MathJax.Hub])`.
>
> A final performance change would be to wipe the `Queue` whenever a user switches away from an article so it doesn’t get hung-up on a backlog of articles that have already been read.

Cheers, :slightly_smiling_face:

**Comment by benubois** [comment]
When I last looked at MathJax a few years ago I ruled it out for a few reasons. 

- It felt heavy. An additional script download + fonts and resources if it needs. Render performance also felt clunky.
- Too many embed methods to support  TeX, LaTeX, MathML, AsciiMath. TeX and AsciiMath worry me since they're just text on the page. False positives seem likely here.
- Security. I'm not clear on the the security of MathJax. However unlikely it is that someone could attack Feedbin customers through their RSS subscriptions I'm not interested in taking any risks here. I do not understand how MathJax works and what the security considerations are for evaluating expressions from untrusted sources.

If anyone has solutions for these concerns I can re-evaluate this.
