### ISSUE TITLE
Feed images missing

### ISSUE THREAD

**Issue by fharbe** [feedbin/support#447]
The RSS feed of the site "mobilegeeks.de" is missing images since ~3 days now.
I never noticed the issue before, I believe it has something to do with camo.

The Feed url is
http://www.mobilegeeks.de/feed/
or also
http://feeds.feedburner.com/netbooknewsde

This image [0] shows up, [1] does not.

[0] https://camo-feedbin.herokuapp.com/416e5eb2f0178d2bc03a99c07aa023ea1ad38daa/687474703a2f2f7777772e6d6f62696c656765656b732e64652f77702d636f6e74656e742f75706c6f6164732f323031342f30352f4c69717569642d4c6561702d546974656c2e6a7067
[1] https://camo-feedbin.herokuapp.com/fbc3d5c0be546c4d362f97ebe54d56ecc8fd3542/687474703a2f2f7777772e6d6f62696c656765656b732e64652f77702d636f6e74656e742f75706c6f6164732f323031342f30352f616365722d6c69717569642d78312d7465617365722e6a7067

greetings, Florian

**Comment by MikhailTNY** [comment]
No progress or any news from Ben here?

I get faster image downloads from the original sites than I do from heroku that Feedbin is using as part of the image caching. There should be an option to disable the use of heroku cache.

**Comment by MikhailTNY** [comment]
Wait, come to think of this, Ben might not be able to do this because the https security. That's likely the reason he's caching them behind his site's control, so he can serve them over https://feedbin.com. 

Even if Ben allows an option to disable the images, you're required to use Feedbin on http:// protocol or otherwise the browsers will block the secure content IIRC.

**Comment by benubois** [comment]
There is now an option to disable the image proxy on https://feedbin.com/settings towards the bottom.

The reason for the proxy is to prevent [mixed content security issues](https://developer.mozilla.org/en-US/docs/Security/MixedContent).

However between the image proxy not working in 100% of cases, the speed decrease due to the extra network hop and overzealous IT departments like @gaborlenard's I think it makes sense to have the option to disable this.

**Comment by gaborlenard** [comment]
Thank you so much, Ben! This is indeed a great improvement for my special work environment, and I am very grateful for the change.

**Comment by MikhailTNY** [comment]
TY. Images are definitely much faster to load with the option turned off. 

Thanks Ben!
