### ISSUE TITLE
Already-read entries coming back for Longform.org feed

### ISSUE THREAD

**Issue by eliahhecht** [feedbin/support#515]
Periodically, I will see a bunch of old entries from `http://longform.org/feed.rss`, ones that I have already marked as read, show up in my feedbin as unread.

**Comment by benubois** [comment]
Hi @eliahhecht ,

I took a look at the feed I think I found the issue.

RSS feeds generally have ids associated with each article to help feed readers identify unique content. In the source code this looks something like:

```xml
<guid isPermaLink="false">https://longform.org/posts/8491</guid>
```

Unfortunately it looks like this website sometimes changes ids for example the above shows up in Feedbin twice with different ids:

1. `https://longform.org/posts/8491`
2. `http://longform.org/posts/8491`

In these cases this must be fixed by the publisher of the feed.

Thanks!

**Comment by wam** [comment]
@benubois @eliahhecht thanks for bringing this to our attention! I'm gonna check it out and try to correct it.
