### ISSUE TITLE
Feature request: automatically convert YouTube URLs

### ISSUE THREAD

**Issue by erunaheru** [feedbin/support#524]
Searching for https://www.youtube.com/channel/UCUK0HBIBWgM2c4vsPhkYY4w should add the feed https://www.youtube.com/feeds/videos.xml?channel_id=UCUK0HBIBWgM2c4vsPhkYY4w

**Comment by benubois** [comment]
Hi @erunaheru,

I'm not sure I'm following. Why is it necessary to convert YouTube URLs? 

When I try subscribe to `https://www.youtube.com/channel/UCUK0HBIBWgM2c4vsPhkYY4w` Feedbin subscribes to the RSS feed advertised by the page's `<link rel="alternate">` attribute.

In this case it is:

```
<link rel="alternate" type="application/rss+xml" title="RSS" href="https://www.youtube.com/feeds/videos.xml?channel_id=UCUK0HBIBWgM2c4vsPhkYY4w">
```

Which is the same as you suggest, however it's important to get this from the page itself incase YouTube wants to change the location of their feeds.

**Comment by erunaheru** [comment]
Sorry, I grabbed that as an example of a popular channel, but not all channels seem to work correctly that way. Here is one that doesn't have the rel tag: https://www.youtube.com/channel/UCjns5cc6SWZWTSr8sgW5dww

**Comment by benubois** [comment]
Oh, Ok, 

I see it now. I'll look into this in that case.

Thanks for pointing this out!

**Comment by MichaelQ** [comment]
Any update on this? I am finding more and more Youtube channels do not seem to have a feed for Feedbin to find.

YouTube URL's with "user" in them seem to work fine. YouTube URL's with "channel" in them seem to fail most of the time lately.

**Comment by Zegnat** [comment]
You can export your YouTube subscriptions as OPML file that Feedbin can import without problems. Just scroll to the bottom of your [subscription manager](https://www.youtube.com/subscription_manager). No hacks needed to import channels.

But I agree that it would be nice if Feedbin could offer some sort of URL pre-parser for services where we know there are RSS feeds available that might not be linked on the actual website. I recall seeing Tumblr blogs without `META` tags as well, while Tumblr generally has RSS enabled at a default URL. So that’s another one that might benefit of such a feature.

**Comment by MichaelQ** [comment]
True @zegnat but I am often chopping and changing my YouTube subscriptions and wouldn't re-adding the "new" OPML file mean I get all the videos I might have recently watched on Feedbin?

Plus I like to split my videos up into folders - WordPress, Google, Entertainment etc. So the individual ones work much better.

**Comment by benubois** [comment]
This is complete. Feedbin will try to convert URLs like:

- https://www.youtube.com/channel/XX
- https://www.youtube.com/user/XX
- https://www.youtube.com/playlist?list=XX

Please let me know if there are any other types of YouTube pages that Feedbin could support.

Thanks!

**Comment by MichaelQ** [comment]
A very belated THANKS for this. Great stuff, Ben.
