### ISSUE TITLE
http://www.evo.co.uk/feeds/all not updating

### ISSUE THREAD

**Issue by JoSpalding** [feedbin/support#528]
Please take a look at this feed. I have subscribed more than a week ago but it is not been updated.

It validates ok on w3c and I can read the contents on other readers.

Thanks in advance.

**Comment by JoSpalding** [comment]
Any chance of anyone from Feedbin to take a look at this? @benubois ?
It's been 9 days since the issue was opened and the feed was never updated since it was subscribed more than 2 weeks ago.

There are other issues much older than this here on github, for related problems with feeds not updating, without any reply or activity. As a paying customer, I expect a minimum level of support for issues with the service.

I'm working on a project that has a high level of dependency on the feeds I'm subscribed, so I need a reliable service that I can trust and, as problems always happens, some kind of support with at least an average response time (more than a week for simple issues is a deal breaker).

All that said, I really like Feedbin and I hope to continue being a customer.

Best regards!

**Comment by benubois** [comment]
Hi @JoSpalding,

Sorry to leave you hanging. Feeds not updating are a relatively low priority, because at this point if a feed is valid atom or RSS 1.0-2.0 and is available over HTTP(S) then Feedbin will update it. Unless a bug is introduced that affects more than just one feed then I assume it is a problem with the feed itself.

In this case it looks like the host of `http://www.evo.co.uk/feeds/all` is blocking Feedbin's refreshing servers. 

```bash
curl -sIL 'http://www.evo.co.uk/feeds/all'
HTTP/1.1 403 Forbidden
Server: nginx
Date: Wed, 02 Dec 2015 21:02:09 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
```

If you like you can report the issue to evo. Feedbin's refreshing servers use the following static IPs:

```
104.131.195.214
104.131.197.228
104.131.199.242
104.131.200.249
107.170.61.36
107.170.62.43
107.170.63.50
162.243.199.26
162.243.69.172
162.243.73.200
```

**Comment by benubois** [comment]
One other thing, if you're looking for feed refreshing as a service then I'd highly recommend [Superfeedr](https://superfeedr.com/)

**Comment by JoSpalding** [comment]
Thank you very much for clarifying the issue and for the recommendation!
