### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by jgmarcel** [feedbin/support#541]
Reproducible steps:

1. Subscribe to the affected feeds (examples follow).
2. Get duplicate items.

Affected feeds:

* https://lifeondoverbeach.wordpress.com/feed/
* https://orthosphere.wordpress.com/feed/
* https://zippycatholic.wordpress.com/feed/

**Comment by benubois** [comment]
Hi @jgmarcel,

Sorry for the trouble. This is a problem caused by WordPress. They are inconsistent with article guids so it causes duplicates in Feedbin. They fixed it on their side in the past and I'm hoping they'll fix it again soon.

There's more information about this issue in #431.

Closing this a a duplicate.

Thanks!
