### ISSUE TITLE
Microsoft Edge Dev Blog entries not showing up

### ISSUE THREAD

**Issue by rik** [feedbin/support#573]
https://gist.github.com/rik/e784cf5f56d8a1b60c7d27eb6a3032e4

Latest entries are from this week but Feedbin Feed page only lists those:
Jan 13: ChakraCore’s first anniversary
Jan 13: ChakraCore’s first anniversary
Jan 10: Introducing support for Content Security Policy Level 2

**Comment by benubois** [comment]
Hi @rik,

Sorry for the trouble! I took a look at the feed and I think I see the issue. 

RSS feeds generally have IDs associated with each article to help feed readers identify unique content. In the source code this looks something like:

```xml
<guid>the id</guid>
```

However with this feed it looks like the ID is the same on every article:

```xml
<guid isPermaLink="false">http://blogs.windows.com/msedgedev/</guid>
<guid isPermaLink="false">http://blogs.windows.com/msedgedev/</guid>
```

So to Feedbin, every article looks like a duplicate. 

I'm guessing they made a change in January because it worked ok until then. Unfortunately there’s nothing I can do to fix this on Feedbin’s side and it needs to be fixed by the publisher.

Thanks!

Ben

**Comment by rik** [comment]
Ah sorry for this, I could have ran a feed check before opening an issue here. Thanks for the quick answer.

Maybe you could update http://help.feedbin.com/debugging-feeds/ to ask people to run through a validator before filing issues. That could probably reduce the burden for you?

I've reached out to the authors to try and get it fixed: https://twitter.com/rik24d/status/847890361230004225

**Comment by benubois** [comment]
@rik, A bunch of new articles showed up in Microsoft Edge Dev Blog today so I'm guessing your prompting got it fixed. Thanks!

**Comment by rik** [comment]
[They were already aware](https://twitter.com/kylealden/status/847951816432033792) and your analysis helped so it's cool that it's been fixed so quickly.
