### ISSUE TITLE
RSS feeds duplicates

### ISSUE THREAD

**Issue by Cragh** [feedbin/support#580]
Hello!

Iam trying to subscribe on:

https://www.ehalsomyndigheten.se/driftinformation/rss/ and https://www.ehalsomyndigheten.se/nyheter/rss

But they only show duplicates of one item. Is there something wrong with the XML structure? They both validate as Atom 1.0 feeds.

**Comment by benubois** [comment]
Feedbin uses the `<guid>` (when available) to uniquely identify articles .

As far as I can tell this feed returns a different `<guid>` randomly. For example the  post "Servicefönster - 2017-03-18 08:00 - 2017-03-18 19:00" shows up many times in Feedbin, but each has a unique `<guid>`:

```
uuid:e36303e9-6d13-4e03-9916-62b466775a47;id=1496
uuid:e781ed9f-bc1a-4422-9703-efedcbd79beb;id=645
```

Unfortunately this issue would need to be fixed by the feed publisher.

Thanks!

**Comment by Cragh** [comment]
Iam the feed publisher 💃 

It seems strange to me tho that the same article can pop up with different id seeing how if you just look at the raw xml there is only one instance of that article with one id.

Trying to figure out how iam supposed to stop it from creating dupes when there are no dupes in the XML created on the site :/

**Comment by Cragh** [comment]
It worked after i changed the code a bit :) the URL was just cached so i thought the problem persisted. Right now iam waiting for the cache to refresh on feedbin. Meanwhiles iam using a querystring to get non-cached version when i subscribe.
