### ISSUE TITLE
Management of newsletter subscriptions

### ISSUE THREAD

**Issue by AnimusAstralis** [feedbin/support#583]
Recently, I've accidentally removed several newsletter subscriptions, just like I would remove an RSS feed. I didn't click 'unsubscribe' links in the letters themselves, I just clicked 'delete' on Feedbin's interface. If I understand it correctly, Feedbin now considers these senders blacklisted or something, because it stopped receiving new emails.

We should be able to change a newsletter address to resubscribe or somehow manage deleted subscriptions.

**Comment by jgierer12** [comment]
I have the same problem. Any news?

**Comment by klickreflex** [comment]
I have the exact same problem: tried Feedbin for Newsletters a while ago, then removed all subscriptions from Feedbin to go back to regular email and now I'd like to give Feedbin another shot at managing my Newsletters only to find out there's no way to receive those emails again with Feedbin.

**Comment by benubois** [comment]
Sorry for the trouble!

This can happen if you have previously unsubscribed from this email sender. When you unsubscribe, Feedbin blocks future deliveries from this sender because it's the only way to not get future emails.

There is a workaround. You can resubscribe using a variation of your newsletter address. For example:

YOUR_TOKEN+ANYTHING@newsletters.feedbin.com

This will be improved in the future.
