### ISSUE TITLE
Kent C. Dodds feed not updating

### ISSUE THREAD

**Issue by jgierer12** [feedbin/support#597]
[Gist](https://gist.github.com/jgierer12/e4e92eefddd14f1ace4f671f4507365d)

The latest article is from July 19, but the feed on Feedbin hasn't been updated since July 8.

**Comment by benubois** [comment]
Hi @jgierer12,

I took a look at the feed and everything looks correct. The reason this post appears to be missing is because it is a repost of an article with the exact same title and more importantly `guid` as an article post on July 16, 2018.

The `guid` uniquely identifies an article which is how feed readers figure out what is new.

If you scroll back in time or search for it you'll find the post in the feed.

<img width="1440" alt="Screen Shot 2019-07-22 at 5 40 47 PM" src="https://user-images.githubusercontent.com/133809/61645813-dd127100-aca7-11e9-9bbf-e3d71db5302c.png">

**Comment by jgierer12** [comment]
Hmm, what about the next post though? As far as I can see it has both a unique title (`Write tests. Not too many. Mostly integration.`) and GUID (`https://kentcdodds.com/blog/write-tests`). Shouldn't that at least be displayed?

**Comment by benubois** [comment]
From 2017:

<img width="1441" alt="Screen Shot 2019-07-23 at 1 15 07 PM" src="https://user-images.githubusercontent.com/133809/61707982-f8cf5300-ad4b-11e9-91cd-2ccfd2520f72.png">

**Comment by jgierer12** [comment]
Ah, I see. Would it be possible to add a per-feed setting to display the articles in chronological order (as they appear in the feed)?
