### ISSUE TITLE
Doesn't include the latest posting on DreamHost Blog Posts

### ISSUE THREAD

**Issue by yphoenix** [feedbin/support#604]
When I use the DreamHost feed:

https://www.dreamhost.com/blog/feed/

The latest message (Jan 9th) is not displayed, older posts are.

Gist: https://gist.github.com/yphoenix/27f45f74c07eb8f069d8751a6c611bf4

**Comment by benubois** [comment]
The latest article, “The 10 Best Web Management Tools for Small Businesses in 2020” appears to be an update to the 2017 article “The 7 Best Web Management Tools for Small Business...”

The issue here is the way Dreamhost chose to do this.

Both articles share a common `<guid>` which is meant to uniquely identify articles. RSS readers use this to determine if they already have a copy of the article or not. Feedbin already has the 2017 article so this new one appears to be a duplicate.

**Comment by yphoenix** [comment]
Thanks for solving this. Hadn’t spotted the duplicate guid. A dilemma to know what to do if an article gets updated with a new pubDate. Re-show it to the user or ignore it?
